import { useEffect, useState } from 'react';
import { MessageSquare, Send, Trash2 } from 'lucide-react';
import api, { getErrorMessage } from '../services/api';
import { useApp } from '../context/AppContext';
import { Avatar, Badge, Loading, Modal } from './UI';

const emptyIssue = { title: '', description: '', type: 'task', priority: 'medium', status: 'todo', assignee_id: '', sprint_id: '' };

export function IssueFormModal({ open, onClose, issue, users, sprints, onSaved, initialSprintId = '' }) {
  const { selectedProjectId, notify } = useApp();
  const [form, setForm] = useState(emptyIssue); const [saving, setSaving] = useState(false);
  useEffect(() => { setForm(issue ? { title: issue.title, description: issue.description || '', type: issue.type, priority: issue.priority, status: issue.status, assignee_id: issue.assignee_id || '', sprint_id: '' } : { ...emptyIssue, sprint_id: initialSprintId || '' }); }, [issue, open, initialSprintId]);
  const submit = async (e) => { e.preventDefault(); setSaving(true); try { const body = { ...form, project_id: Number(selectedProjectId), assignee_id: form.assignee_id ? Number(form.assignee_id) : null, ...(form.sprint_id && !issue ? { sprint_id: Number(form.sprint_id) } : {}) }; const { data } = issue ? await api.patch(`/issues/${issue.id}`, body) : await api.post('/issues', body); notify(data.message); onSaved(); onClose(); } catch (err) { notify(getErrorMessage(err), 'error'); } finally { setSaving(false); } };
  return <Modal open={open} onClose={onClose} title={issue ? `Edit ${issue.issue_key || 'issue'}` : 'Create issue'} subtitle={issue ? 'Update the work item and ownership.' : 'Add a new item to the selected project.'} size="large"><form className="form-stack" onSubmit={submit}><label>Title<input autoFocus value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="What needs to be done?" required /></label><label>Description<textarea rows="5" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Add context, acceptance criteria or useful links..." /></label><div className="form-grid-3"><label>Type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="task">Task</option><option value="story">Story</option><option value="bug">Bug</option></select></label><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select></label></div><div className="form-row"><label>Assignee<select value={form.assignee_id} onChange={(e) => setForm({ ...form, assignee_id: e.target.value })}><option value="">Unassigned</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label>{!issue && <label>Sprint<select value={form.sprint_id} onChange={(e) => setForm({ ...form, sprint_id: e.target.value })}><option value="">Backlog</option>{sprints.filter((s) => s.status !== 'completed').map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}</div><div className="form-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? 'Saving...' : issue ? 'Save changes' : 'Create issue'}</button></div></form></Modal>;
}

export function IssueDetailModal({ issueId, onClose, users, onChanged }) {
  const { user, notify } = useApp();
  const [issue, setIssue] = useState(null); const [comments, setComments] = useState([]); const [content, setContent] = useState(''); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { if (!issueId) return; setLoading(true); try { const [issueRes, commentRes] = await Promise.all([api.get(`/issues/${issueId}`), api.get(`/comments?issue_id=${issueId}`)]); setIssue(issueRes.data.issue); setComments(commentRes.data.comments); } catch (err) { notify(getErrorMessage(err), 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [issueId]); // eslint-disable-line react-hooks/exhaustive-deps
  const addComment = async (e) => { e.preventDefault(); if (!content.trim()) return; try { await api.post('/comments', { issue_id: issueId, content }); setContent(''); load(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  const deleteComment = async (id) => { try { await api.delete(`/comments/${id}`); setComments((current) => current.filter((c) => c.id !== id)); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  const removeIssue = async () => { if (!window.confirm('Delete this issue permanently?')) return; try { const { data } = await api.delete(`/issues/${issueId}`); notify(data.message); onChanged(); onClose(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  return <><Modal open={Boolean(issueId)} onClose={onClose} title={issue?.issue_key || 'Issue details'} subtitle={issue?.title} size="large">{loading ? <Loading /> : issue && <div className="issue-detail"><div className="issue-detail-main"><div className="detail-title-row"><h3>{issue.title}</h3><Badge tone={issue.priority}>{issue.priority}</Badge></div><p className="detail-description">{issue.description || 'No description provided.'}</p><div className="detail-meta"><div><span>Status</span><Badge tone={issue.status}>{issue.status.replace('_', ' ')}</Badge></div><div><span>Type</span><strong>{issue.type}</strong></div><div><span>Assignee</span>{issue.assignee ? <span className="person-inline"><Avatar name={issue.assignee.name} size="sm" />{issue.assignee.name}</span> : <strong>Unassigned</strong>}</div><div><span>Created by</span><strong>{issue.creator?.name || 'Unknown'}</strong></div></div><div className="detail-actions"><button className="button button-secondary" onClick={() => setEditing(true)}>Edit issue</button><button className="button button-danger" onClick={removeIssue}><Trash2 size={16} />Delete</button></div></div><section className="comments-section"><div className="section-title"><MessageSquare size={18} /><h3>Activity</h3><span>{comments.length}</span></div><div className="comments-list">{comments.map((comment) => <article className="comment" key={comment.id}><Avatar name={comment.author?.name} size="sm" /><div><header><strong>{comment.author?.name}</strong><time>{new Date(comment.created_at).toLocaleString()}</time>{Number(comment.user_id) === Number(user.id) && <button onClick={() => deleteComment(comment.id)} title="Delete comment"><Trash2 size={14} /></button>}</header><p>{comment.content}</p></div></article>)}{!comments.length && <p className="muted">No comments yet.</p>}</div><form className="comment-form" onSubmit={addComment}><Avatar name={user.name} size="sm" /><div><textarea rows="2" value={content} onChange={(e) => setContent(e.target.value)} placeholder="Write a comment..." /><button className="icon-button icon-button-primary" aria-label="Send comment"><Send size={16} /></button></div></form></section></div>}</Modal>{issue && <IssueFormModal open={editing} onClose={() => setEditing(false)} issue={issue} users={users} sprints={[]} onSaved={() => { load(); onChanged(); }} />}</>;
}
