import { useEffect, useMemo, useState } from 'react';
import { Filter, ListFilter, Plus, Search } from 'lucide-react';
import api, { getErrorMessage } from '../services/api';
import { useApp } from '../context/AppContext';
import { Avatar, Badge, EmptyState, Loading } from '../components/UI';
import { IssueDetailModal, IssueFormModal } from '../components/IssueModal';

export default function Backlog() {
  const { selectedProject, selectedProjectId, notify } = useApp();
  const [issues, setIssues] = useState([]); const [users, setUsers] = useState([]); const [sprints, setSprints] = useState([]); const [loading, setLoading] = useState(true); const [createOpen, setCreateOpen] = useState(false); const [detailId, setDetailId] = useState(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [priority, setPriority] = useState('all');
  const load = async () => { if (!selectedProjectId) { setIssues([]); setLoading(false); return; } setLoading(true); try { const [a, b, c] = await Promise.all([api.get(`/issues?project_id=${selectedProjectId}`), api.get('/users'), api.get(`/sprints?project_id=${selectedProjectId}`)]); setIssues(a.data.issues); setUsers(b.data.users); setSprints(c.data.sprints); } catch (err) { notify(getErrorMessage(err), 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [selectedProjectId]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered = useMemo(() => issues.filter((i) => (status === 'all' || i.status === status) && (priority === 'all' || i.priority === priority) && `${i.issue_key} ${i.title}`.toLowerCase().includes(search.toLowerCase())), [issues, search, status, priority]);
  return <div className="page-content"><header className="page-header"><div><span className="eyebrow">{selectedProject?.key || 'No project selected'}</span><h1>Backlog</h1><p>Capture, prioritize and assign all upcoming work.</p></div><button className="button button-primary" onClick={() => setCreateOpen(true)} disabled={!selectedProjectId}><Plus size={17} />Create issue</button></header>
    <div className="toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search issues..." /></div><div className="filter-control"><ListFilter size={16} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select></div><div className="filter-control"><Filter size={16} /><select value={priority} onChange={(e) => setPriority(e.target.value)}><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div><span className="result-count">{filtered.length} issues</span></div>
    {loading ? <Loading /> : !selectedProjectId ? <EmptyState title="Select a project" text="Choose a project from the sidebar to view its backlog." /> : !filtered.length ? <EmptyState title="No matching issues" text="Create an issue or adjust the current filters." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Issue</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Created</th></tr></thead><tbody>{filtered.map((issue) => <tr key={issue.id} onClick={() => setDetailId(issue.id)}><td><div className="issue-cell"><span className={`issue-type issue-type-${issue.type}`}>{issue.type[0].toUpperCase()}</span><div><strong>{issue.title}</strong><span>{issue.issue_key} · {issue.type}</span></div></div></td><td><Badge tone={issue.status}>{issue.status.replace('_', ' ')}</Badge></td><td><Badge tone={issue.priority}>{issue.priority}</Badge></td><td>{issue.assignee ? <span className="person-inline"><Avatar name={issue.assignee.name} size="sm" />{issue.assignee.name}</span> : <span className="muted">Unassigned</span>}</td><td className="muted">{new Date(issue.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
    <IssueFormModal open={createOpen} onClose={() => setCreateOpen(false)} users={users} sprints={sprints} onSaved={load} /><IssueDetailModal issueId={detailId} onClose={() => setDetailId(null)} users={users} onChanged={load} />
  </div>;
}
