import { useState } from 'react';
import { Edit3, FolderKanban, MoreHorizontal, Plus, Trash2 } from 'lucide-react';
import api, { getErrorMessage } from '../services/api';
import { useApp } from '../context/AppContext';
import { EmptyState, Modal } from '../components/UI';

const blank = { name: '', key: '', description: '' };
export default function Projects() {
  const { projects, canManage, loadProjects, selectProject, notify } = useApp();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false);
  const showForm = (project = null) => { setEditing(project); setForm(project ? { name: project.name, key: project.key, description: project.description || '' } : blank); setOpen(true); };
  const submit = async (e) => { e.preventDefault(); setSaving(true); try { const res = editing ? await api.patch(`/projects/${editing.id}`, form) : await api.post('/projects', form); notify(res.data.message); await loadProjects(); setOpen(false); } catch (err) { notify(getErrorMessage(err), 'error'); } finally { setSaving(false); } };
  const remove = async (project) => { if (!window.confirm(`Delete ${project.name} and all of its issues and sprints?`)) return; try { const { data } = await api.delete(`/projects/${project.id}`); notify(data.message); await loadProjects(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  return <div className="page-content"><header className="page-header"><div><span className="eyebrow">Workspace structure</span><h1>Projects</h1><p>Separate workstreams and keep every issue in the right context.</p></div>{canManage && <button className="button button-primary" onClick={() => showForm()}><Plus size={17} />New project</button>}</header>
    {!projects.length ? <EmptyState icon={FolderKanban} title="No projects yet" text="Create the first project in this organization." action={canManage && <button className="button button-primary" onClick={() => showForm()}>Create project</button>} /> : <div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.id} onClick={() => selectProject(project.id)}><div className={`project-key project-key-${index % 4}`}>{project.key.slice(0, 2)}</div><div className="project-card-copy"><div><span>{project.key}</span><h2>{project.name}</h2></div><p>{project.description || 'No description has been added yet.'}</p><footer><span>Created {new Date(project.created_at).toLocaleDateString()}</span>{canManage && <div className="card-actions"><button className="icon-button" onClick={(e) => { e.stopPropagation(); showForm(project); }} title="Edit project"><Edit3 size={16} /></button><button className="icon-button danger" onClick={(e) => { e.stopPropagation(); remove(project); }} title="Delete project"><Trash2 size={16} /></button></div>}<MoreHorizontal size={17} /></footer></div></article>)}</div>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit project' : 'Create project'} subtitle="Project keys are used to identify every issue."><form className="form-stack" onSubmit={submit}><div className="form-row"><label>Project name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Key<input value={form.key} maxLength={10} onChange={(e) => setForm({ ...form, key: e.target.value.toUpperCase() })} placeholder="WEB" required /></label></div><label>Description<textarea rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : 'Create project'}</button></div></form></Modal>
  </div>;
}
