import { useEffect, useState } from 'react';
import { CalendarDays, Check, Edit3, Play, Plus, Trash2 } from 'lucide-react';
import api, { getErrorMessage } from '../services/api';
import { useApp } from '../context/AppContext';
import { Badge, EmptyState, Loading, Modal } from '../components/UI';

const blank = { name: '', goal: '', start_date: '', end_date: '' };
export default function Sprints() {
  const { selectedProject, selectedProjectId, canManage, notify } = useApp();
  const [sprints, setSprints] = useState([]); const [issues, setIssues] = useState([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank); const [manageSprint, setManageSprint] = useState(null); const [selectedIssue, setSelectedIssue] = useState('');
  const load = async () => { if (!selectedProjectId) { setSprints([]); setLoading(false); return; } setLoading(true); try { const [s, i] = await Promise.all([api.get(`/sprints?project_id=${selectedProjectId}`), api.get(`/issues?project_id=${selectedProjectId}`)]); setSprints(s.data.sprints); setIssues(i.data.issues); } catch (err) { notify(getErrorMessage(err), 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [selectedProjectId]); // eslint-disable-line react-hooks/exhaustive-deps
  const showForm = (sprint = null) => { setEditing(sprint); setForm(sprint ? { name: sprint.name, goal: sprint.goal || '', start_date: sprint.start_date?.slice(0, 10) || '', end_date: sprint.end_date?.slice(0, 10) || '' } : blank); setOpen(true); };
  const submit = async (e) => { e.preventDefault(); try { const body = { ...form, project_id: Number(selectedProjectId) }; const { data } = editing ? await api.patch(`/sprints/${editing.id}`, body) : await api.post('/sprints', body); notify(data.message); setOpen(false); load(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  const action = async (sprint, type) => { if (type === 'delete' && !window.confirm(`Delete ${sprint.name}?`)) return; try { const { data } = type === 'delete' ? await api.delete(`/sprints/${sprint.id}`) : await api.patch(`/sprints/${sprint.id}/${type}`); notify(data.message); load(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  const addIssue = async () => { if (!selectedIssue) return; try { const { data } = await api.post(`/sprints/${manageSprint.id}/issues`, { issue_id: Number(selectedIssue) }); notify(data.message); setSelectedIssue(''); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  return <div className="page-content"><header className="page-header"><div><span className="eyebrow">{selectedProject?.key || 'Sprint planning'}</span><h1>Sprints</h1><p>Define goals, dates and the delivery window for planned work.</p></div>{canManage && <button className="button button-primary" onClick={() => showForm()} disabled={!selectedProjectId}><Plus size={17} />New sprint</button>}</header>
    {loading ? <Loading /> : !sprints.length ? <EmptyState icon={CalendarDays} title="No sprints yet" text="Create a sprint and start organizing your backlog." action={canManage && <button className="button button-primary" onClick={() => showForm()}>Create sprint</button>} /> : <div className="sprint-list">{sprints.map((sprint) => <article className="sprint-card" key={sprint.id}><div className="sprint-status-line"><Badge tone={sprint.status}>{sprint.status}</Badge><span>{new Date(sprint.created_at).toLocaleDateString()}</span></div><h2>{sprint.name}</h2><p>{sprint.goal || 'No sprint goal has been defined.'}</p><div className="sprint-dates"><CalendarDays size={17} /><span>{sprint.start_date ? new Date(sprint.start_date).toLocaleDateString() : 'Not scheduled'}</span><span>→</span><span>{sprint.end_date ? new Date(sprint.end_date).toLocaleDateString() : 'Open ended'}</span></div><footer><button className="button button-secondary button-small" onClick={() => setManageSprint(sprint)}>Add issues</button>{canManage && <div>{sprint.status === 'planned' && <button className="icon-button success" title="Start sprint" onClick={() => action(sprint, 'start')}><Play size={16} /></button>}{sprint.status === 'active' && <button className="icon-button success" title="Complete sprint" onClick={() => action(sprint, 'complete')}><Check size={16} /></button>}<button className="icon-button" title="Edit sprint" onClick={() => showForm(sprint)}><Edit3 size={16} /></button><button className="icon-button danger" title="Delete sprint" onClick={() => action(sprint, 'delete')}><Trash2 size={16} /></button></div>}</footer></article>)}</div>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit sprint' : 'Create sprint'} subtitle="Set a focused delivery goal and schedule."><form className="form-stack" onSubmit={submit}><label>Sprint name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Goal<textarea rows="3" value={form.goal} onChange={(e) => setForm({ ...form, goal: e.target.value })} /></label><div className="form-row"><label>Start date<input type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /></label><label>End date<input type="date" value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></label></div><div className="form-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary">{editing ? 'Save changes' : 'Create sprint'}</button></div></form></Modal>
    <Modal open={Boolean(manageSprint)} onClose={() => setManageSprint(null)} title={`Add issues to ${manageSprint?.name || 'sprint'}`} subtitle="Choose an issue from this project's backlog."><div className="inline-form"><select value={selectedIssue} onChange={(e) => setSelectedIssue(e.target.value)}><option value="">Select an issue</option>{issues.map((i) => <option key={i.id} value={i.id}>{i.issue_key} · {i.title}</option>)}</select><button className="button button-primary" onClick={addIssue}>Add issue</button></div></Modal>
  </div>;
}
