import { useEffect, useState } from 'react';
import { Mail, Plus, ShieldCheck, Users as UsersIcon } from 'lucide-react';
import api, { getErrorMessage } from '../services/api';
import { useApp } from '../context/AppContext';
import { Avatar, Badge, EmptyState, Loading, Modal } from '../components/UI';

export default function Team() {
  const { user, canManage, notify } = useApp(); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'member' });
  const load = async () => { setLoading(true); try { const { data } = await api.get('/users'); setUsers(data.users); } catch (err) { notify(getErrorMessage(err), 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const create = async (e) => { e.preventDefault(); try { const { data } = await api.post('/users', form); notify(data.message); setOpen(false); setForm({ name: '', email: '', password: '', role: 'member' }); load(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  const changeRole = async (id, role) => { try { const { data } = await api.patch(`/users/${id}/role`, { role }); notify(data.message); load(); } catch (err) { notify(getErrorMessage(err), 'error'); } };
  return <div className="page-content"><header className="page-header"><div><span className="eyebrow">Organization</span><h1>Team</h1><p>Manage access and ownership across your workspace.</p></div>{canManage && <button className="button button-primary" onClick={() => setOpen(true)}><Plus size={17} />Add member</button>}</header>
    {loading ? <Loading /> : !users.length ? <EmptyState icon={UsersIcon} title="No team members" text="Invite the first person into your workspace." /> : <div className="team-grid">{users.map((member) => <article className="member-card" key={member.id}><div className="member-card-top"><Avatar name={member.name} size="lg" /><Badge tone={member.role}>{member.role}</Badge></div><h2>{member.name}{Number(member.id) === Number(user.id) && <span>You</span>}</h2><p><Mail size={15} />{member.email}</p><footer><span>Joined {new Date(member.created_at).toLocaleDateString()}</span>{canManage && Number(member.id) !== Number(user.id) ? <select value={member.role} onChange={(e) => changeRole(member.id, e.target.value)}><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option><option value="owner">Owner</option></select> : <ShieldCheck size={17} />}</footer></article>)}</div>}
    <Modal open={open} onClose={() => setOpen(false)} title="Add team member" subtitle="Create a login for someone in your organization."><form className="form-stack" onSubmit={create}><div className="form-row"><label>Full name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option></select></label></div><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><label>Temporary password<input type="password" minLength="8" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /></label><div className="form-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary">Add member</button></div></form></Modal>
  </div>;
}
